# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# Warnings currently triggered - may want refactoring out
- ignore: {name: "Use notElem"}
- ignore: {name: "Redundant bracket"}
- ignore: {name: "Eta reduce"}
- ignore: {name: "Redundant do"}
- ignore: {name: "Redundant return"}
- ignore: {name: "Redundant $"}
- ignore: {name: "Avoid lambda"}
