sudo: required

os:
- linux
- osx

script:
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
- curl -sSL https://get.haskellstack.org/ | sh
- stack setup > nul
- stack --no-terminal build
- stack runhaskell CI.hs
